name: Static Analysis

on:
  pull_request

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:15-master
        env:
          POSTGRES_DB: actiontest
          POSTGRES_PASSWORD: pass1234
          POSTGRES_USER: the_user
        ports:
          - "5432:5432"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: ~/test_database_dump.sql
          key: ${{ runner.os }}-${{ hashFiles('**/migrations/*.py') }}
      - name: Restore Database
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          echo Restoring Database from backup
          PGPASSWORD=pass1234 psql -U the_user -d actiontest -h localhost -f ~/test_database_dump.sql
      - name: Install Dependencies
        run: |
          # install needed libraries into container
          sudo apt update
          sudo apt install -y gdal-bin
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.11.6'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: Run Tests
        env:
          ENV: testing
        run: |
          python -m pytest -v

